App["Constant"] = {
	"DESKTOP_MINIMUM": 1024,
	"TABLET_MINUMUM": 768,
	"MOBILE_MINIMUM": 425,
	"DEFAULT_CONTROLLER": "home",
	"DEFAULT_ACTION": "index",
	"DEFAULT_TEMPLATE": "template",
	"PREFIX": ""
}